GET http://localhost:4000/candos/
###

GET http://localhost:4000/candos/ByLevel/B1
###

POST http://localhost:4000/candos/
Content-Type: application/json

{
  "number": 2,
  "name": "Reconhecer caracteres japoneses: Katakana",
  "lesson": "Lição 2",
  "level": "A1"
}
###

PUT http://localhost:4000/candos/624da61957237cfac075b841
Content-Type: application/json

{
  "number": 1,
  "name": "Reconhecer caracteres japoneses: Hiragana",
  "lesson": "Lição 1",
  "level": "A1"
}
###

DELETE http://localhost:4000/candos/624e10f9cc50bdb65ac2b648



###
GET http://localhost:4000/questions/getPopulated/62fc3e4e8123a75f0d67c477
###

###
GET http://localhost:4000/answers/
###
GET http://localhost:4000/questions/
###
DELETE http://localhost:4000/answers/all
###
DELETE http://localhost:4000/questions/all
###




GET http://localhost:4000/exercises/
###
GET http://localhost:4000/exercises/624e110bcc50bdb65ac2b64a
###
GET http://localhost:4000/exercises/ByCanDo/62fadd49340a4fa60d0c4f50
###


GET http://localhost:4000/exercises/getPopulated/ByCanDo/62fadd57340a4fa60d0c4f52
###
GET http://localhost:4000/exercises/createQuestionsDB/ByCanDo/62fadd57340a4fa60d0c4f52
###

POST http://localhost:4000/exercises/
Content-Type: application/json

{
  "index_val": 1,
    "name": "Leitura de Katakana #1",
    "description": "Escolha a alternativa correta com a leitura em ROOMAJI (Caractér romano) e significado em Português.",
    "questions": [
      {
        "question": "ロシア",
        "skill_model_unificado": 1,
        "skill_model_semi_unificado": 2,
        "skill_model_granular": 2,
        "answers": [
          {
            "text": "DOITSU - Alemanhã",
            "correct": false,
            "_id": "62d5d4b4971f290a664b1019"
          },
          {
            "text": "ROSHIA - Rússia",
            "correct": true,
            "_id": "62d5d4b4971f290a664b101a"
          },
          {
            "text": "KANADA - Canadá",
            "correct": false,
            "_id": "62d5d4b4971f290a664b101b"
          }
        ],
        "_id": "62d5d4b4971f290a664b1018"
      },
      {
        "question": "アメリカ",
        "skill_model_unificado": 1,
        "skill_model_semi_unificado": 2,
        "skill_model_granular": 2,
        "answers": [
          {
            "text": "AMERICA - América / Estados Unidos",
            "correct": true,
            "_id": "62d5d4b4971f290a664b101d"
          },
          {
            "text": "IGIRISU - Inglaterra",
            "correct": false,
            "_id": "62d5d4b4971f290a664b101e"
          },
          {
            "text": "ITARIA - Itália",
            "correct": false,
            "_id": "62d5d4b4971f290a664b101f"
          }
        ],
        "_id": "62d5d4b4971f290a664b101c"
      },
      {
        "question": "イギリス",
        "skill_model_unificado": 1,
        "skill_model_semi_unificado": 2,
        "skill_model_granular": 2,
        "answers": [
          {
            "text": "SUPEIN - Espanha",
            "correct": false,
            "_id": "62d5d4b4971f290a664b1021"
          },
          {
            "text": "EGIPUTO - Egito",
            "correct": false,
            "_id": "62d5d4b4971f290a664b1022"
          },
          {
            "text": "IGIRISU - Inglaterra",
            "correct": true,
            "_id": "62d5d4b4971f290a664b1023"
          }
        ],
        "_id": "62d5d4b4971f290a664b1020"
      },
      {
        "question": "ブラジル",
        "skill_model_unificado": 1,
        "skill_model_semi_unificado": 2,
        "skill_model_granular": 2,
        "answers": [
          {
            "text": "FURANSU - França",
            "correct": false,
            "_id": "62d5d4b4971f290a664b1025"
          },
          {
            "text": "MEKISHIKO - México",
            "correct": false,
            "_id": "62d5d4b4971f290a664b1026"
          },
          {
            "text": "BURAJIRU - Brasil",
            "correct": true,
            "_id": "62d5d4b4971f290a664b1027"
          }
        ],
        "_id": "62d5d4b4971f290a664b1024"
      },
      {
        "question": "ドイツ",
        "skill_model_unificado": 1,
        "skill_model_semi_unificado": 2,
        "skill_model_granular": 2,
        "answers": [
          {
            "text": "DOITSU - Alemanhã",
            "correct": true,
            "_id": "62d5d4b4971f290a664b1029"
          },
          {
            "text": "INDO - Índia",
            "correct": false,
            "_id": "62d5d4b4971f290a664b102a"
          },
          {
            "text": "KANADA - Canadá",
            "correct": false,
            "_id": "62d5d4b4971f290a664b102b"
          }
        ],
        "_id": "62d5d4b4971f290a664b1028"
      },
      {
        "question": "インドネシア",
        "skill_model_unificado": 1,
        "skill_model_semi_unificado": 2,
        "skill_model_granular": 2,
        "answers": [
          {
            "text": "OOSUTORARIA - Austrália",
            "correct": false,
            "_id": "62d5d4b4971f290a664b102d"
          },
          {
            "text": "INDONESHIA - Indonésia",
            "correct": true,
            "_id": "62d5d4b4971f290a664b102e"
          },
          {
            "text": "MAREESHIA - Malásia",
            "correct": false,
            "_id": "62d5d4b4971f290a664b102f"
          }
        ],
        "_id": "62d5d4b4971f290a664b102c"
      },
      {
        "question": "フィリピン",
        "skill_model_unificado": 1,
        "skill_model_semi_unificado": 2,
        "skill_model_granular": 2,
        "answers": [
          {
            "text": "FIRIPIN - Filipinas",
            "correct": true,
            "_id": "62d5d4b4971f290a664b1031"
          },
          {
            "text": "BETONAMU - Vietnã",
            "correct": false,
            "_id": "62d5d4b4971f290a664b1032"
          },
          {
            "text": "EJUPUTO - Egito",
            "correct": false,
            "_id": "62d5d4b4971f290a664b1033"
          }
        ],
        "_id": "62d5d4b4971f290a664b1030"
      },
      {
        "question": "イタリア",
        "skill_model_unificado": 1,
        "skill_model_semi_unificado": 2,
        "skill_model_granular": 2,
        "answers": [
          {
            "text": "ITARIA - Itália",
            "correct": true,
            "_id": "62d5d4b4971f290a664b1035"
          },
          {
            "text": "AMERIKA - América / Estados Unidos",
            "correct": false,
            "_id": "62d5d4b4971f290a664b1036"
          },
          {
            "text": "BURAJIRU - Brasil",
            "correct": false,
            "_id": "62d5d4b4971f290a664b1037"
          }
        ],
        "_id": "62d5d4b4971f290a664b1034"
      },
      {
        "question": "エジプト",
        "skill_model_unificado": 1,
        "skill_model_semi_unificado": 2,
        "skill_model_granular": 2,
        "answers": [
          {
            "text": "MEKISHIKO - México",
            "correct": false,
            "_id": "62d5d4b4971f290a664b1039"
          },
          {
            "text": "IGIRISU - Inglaterra",
            "correct": false,
            "_id": "62d5d4b4971f290a664b103a"
          },
          {
            "text": "EJIPUTO - Egito",
            "correct": true,
            "_id": "62d5d4b4971f290a664b103b"
          }
        ],
        "_id": "62d5d4b4971f290a664b1038"
      },
      {
        "question": "カナダ",
        "skill_model_unificado": 1,
        "skill_model_semi_unificado": 2,
        "skill_model_granular": 2,
        "answers": [
          {
            "text": "ROSHIA - Rússia",
            "correct": false,
            "_id": "62d5d4b4971f290a664b103d"
          },
          {
            "text": "KANADA - Canadá",
            "correct": true,
            "_id": "62d5d4b4971f290a664b103e"
          },
          {
            "text": "INDO - Indonésia",
            "correct": false,
            "_id": "62d5d4b4971f290a664b103f"
          }
        ],
        "_id": "62d5d4b4971f290a664b103c"
      },
      {
        "question": "エアコン",
        "skill_model_unificado": 1,
        "skill_model_semi_unificado": 2,
        "skill_model_granular": 2,
        "answers": [
          {
            "text": "EAKON - Ar-condicionado",
            "correct": true,
            "_id": "62d5d4b4971f290a664b1041"
          },
          {
            "text": "TEEBURU - Mesa",
            "correct": false,
            "_id": "62d5d4b4971f290a664b1042"
          },
          {
            "text": "HOTERU - Hotel",
            "correct": false,
            "_id": "62d5d4b4971f290a664b1043"
          }
        ],
        "_id": "62d5d4b4971f290a664b1040"
      },
      {
        "question": "ソファ",
        "skill_model_unificado": 1,
        "skill_model_semi_unificado": 2,
        "skill_model_granular": 2,
        "answers": [
          {
            "text": "SHAWA - Chuveiro",
            "correct": false,
            "_id": "62d5d4b4971f290a664b1045"
          },
          {
            "text": "SOFA - Sofá",
            "correct": true,
            "_id": "62d5d4b4971f290a664b1046"
          },
          {
            "text": "TOIRE - Vaso Sanitário",
            "correct": false,
            "_id": "62d5d4b4971f290a664b1047"
          }
        ],
        "_id": "62d5d4b4971f290a664b1044"
      },
      {
        "question": "カタカナ",
        "skill_model_unificado": 1,
        "skill_model_semi_unificado": 2,
        "skill_model_granular": 2,
        "answers": [
          {
            "text": "TAKUSHII - Táxi",
            "correct": false,
            "_id": "62d5d4b4971f290a664b1049"
          },
          {
            "text": "KATAKANA - Katakana",
            "correct": true,
            "_id": "62d5d4b4971f290a664b104a"
          },
          {
            "text": "RESUTORAN - Restaurante",
            "correct": false,
            "_id": "62d5d4b4971f290a664b104b"
          }
        ],
        "_id": "62d5d4b4971f290a664b1048"
      },
      {
        "question": "コーヒー",
        "skill_model_unificado": 1,
        "skill_model_semi_unificado": 2,
        "skill_model_granular": 2,
        "answers": [
          {
            "text": "TAKUSHII - Táxi",
            "correct": false,
            "_id": "62d5d4b4971f290a664b104d"
          },
          {
            "text": "PAATHII - Festa",
            "correct": false,
            "_id": "62d5d4b4971f290a664b104e"
          },
          {
            "text": "KOOHII - Café",
            "correct": true,
            "_id": "62d5d4b4971f290a664b104f"
          }
        ],
        "_id": "62d5d4b4971f290a664b104c"
      },
      {
        "question": "ピアノ",
        "skill_model_unificado": 1,
        "skill_model_semi_unificado": 2,
        "skill_model_granular": 2,
        "answers": [
          {
            "text": "PIANO - Piano",
            "correct": true,
            "_id": "62d5d4b4971f290a664b1051"
          },
          {
            "text": "KAMERA - Câmera fotográfica",
            "correct": false,
            "_id": "62d5d4b4971f290a664b1052"
          },
          {
            "text": "TEREBI - Tevelisão",
            "correct": false,
            "_id": "62d5d4b4971f290a664b1053"
          }
        ],
        "_id": "62d5d4b4971f290a664b1050"
      },
      {
        "question": "ベッド",
        "skill_model_unificado": 1,
        "skill_model_semi_unificado": 2,
        "skill_model_granular": 2,
        "answers": [
          {
            "text": "SHATSU - Saia",
            "correct": false,
            "_id": "62d5d4b4971f290a664b1055"
          },
          {
            "text": "PAN - Pão",
            "correct": false,
            "_id": "62d5d4b4971f290a664b1056"
          },
          {
            "text": "BEDDO - Cama",
            "correct": true,
            "_id": "62d5d4b4971f290a664b1057"
          }
        ],
        "_id": "62d5d4b4971f290a664b1054"
      },
      {
        "question": "パーティー",
        "skill_model_unificado": 1,
        "skill_model_semi_unificado": 2,
        "skill_model_granular": 2,
        "answers": [
          {
            "text": "TAKUSHII - Táxi",
            "correct": false,
            "_id": "62d5d4b4971f290a664b1059"
          },
          {
            "text": "PAATHII - Festa",
            "correct": true,
            "_id": "62d5d4b4971f290a664b105a"
          },
          {
            "text": "KOOHII - Café",
            "correct": false,
            "_id": "62d5d4b4971f290a664b105b"
          }
        ],
        "_id": "62d5d4b4971f290a664b1058"
      },
      {
        "question": "カラオケ",
        "skill_model_unificado": 1,
        "skill_model_semi_unificado": 2,
        "skill_model_granular": 2,
        "answers": [
          {
            "text": "KARAOKE - Karaokê",
            "correct": true,
            "_id": "62d5d4b4971f290a664b105d"
          },
          {
            "text": "KATAKANA - Katakana",
            "correct": false,
            "_id": "62d5d4b4971f290a664b105e"
          },
          {
            "text": "RESUTORAN - Restaurante",
            "correct": false,
            "_id": "62d5d4b4971f290a664b105f"
          }
        ],
        "_id": "62d5d4b4971f290a664b105c"
      },
      {
        "question": "ジュース",
        "skill_model_unificado": 1,
        "skill_model_semi_unificado": 2,
        "skill_model_granular": 2,
        "answers": [
          {
            "text": "SHATSU - Saia",
            "correct": false,
            "_id": "62d5d4b4971f290a664b1061"
          },
          {
            "text": "JUUSU - Suco",
            "correct": true,
            "_id": "62d5d4b4971f290a664b1062"
          },
          {
            "text": "SHAWAA - Chuveiro",
            "correct": false,
            "_id": "62d5d4b4971f290a664b1063"
          }
        ],
        "_id": "62d5d4b4971f290a664b1060"
      },
      {
        "question": "ホテル",
        "skill_model_unificado": 1,
        "skill_model_semi_unificado": 2,
        "skill_model_granular": 2,
        "answers": [
          {
            "text": "TOIRE - Vaso Sanitário",
            "correct": false,
            "_id": "62d5d4b4971f290a664b1065"
          },
          {
            "text": "TEBURU - Mesa",
            "correct": false,
            "_id": "62d5d4b4971f290a664b1066"
          },
          {
            "text": "HOTERU - Hotel",
            "correct": true,
            "_id": "62d5d4b4971f290a664b1067"
          }
        ],
        "_id": "62d5d4b4971f290a664b1064"
      }
    ],
    "cando_id": "62fadd57340a4fa60d0c4f52"
}

###

PUT http://localhost:4000/exercises/62fba86035e8d585042a7802
Content-Type: application/json

{

}
###

###
DELETE http://localhost:4000/exercises/62fc3e2d8123a75f0d67c2d2
###


POST http://localhost:4000/reports/
Content-Type: application/json

{
  "idUser": "62b4edfcb22b0cf44db5e5ff",
  "idCanDo": "62fadd49340a4fa60d0c4f50",
  "answers": [
    {
      "idAnswerSelected": "6307da6219a0091135472055",
      "idQuestion": "6307da6219a0091135472155",
      "idExercise": "6307da0519a0091135471f5e",
      "score": 1,
      "initialTime": "2022-08-17T15:48:47.561660762",
      "finalTime": "2022-08-17T15:48:48.462660762",
      "_id": "62fd38376f2a2de7a412b760"
    },
    {
      "idAnswerSelected": "6307da6219a0091135472055",
      "idQuestion": "6307da6219a0091135472155",
      "idExercise": "6307da0519a0091135471f5e",
      "score": 1,
      "initialTime": "2022-08-17T15:48:47.561660762",
      "finalTime": "2022-08-17T15:48:48.462660762",
      "_id": "62fd38376f2a2de7a412b760"
    },
    
    {
      "idAnswerSelected": "6307da6219a0091135472055",
      "idQuestion": "6307da6219a0091135472155",
      "idExercise": "6307da0519a0091135471f5e",
      "score": 0,
      "initialTime": "2022-08-17T15:48:47.561660762",
      "finalTime": "2022-08-17T15:48:48.462660762",
      "_id": "62fd38376f2a2de7a412b760"
    },
    {
      "idAnswerSelected": "6307da6219a0091135472055",
      "idQuestion": "6307da6219a0091135472155",
      "idExercise": "6307da0519a0091135471f5e",
      "score": 1,
      "initialTime": "2022-08-17T15:48:47.561660762",
      "finalTime": "2022-08-17T15:48:48.462660762",
      "_id": "62fd38376f2a2de7a412b760"
    },
    {
      "idAnswerSelected": "6307da6e19a0091135472238",
      "idQuestion": "6307da6e19a00911354722b0",
      "idExercise": "6307da3619a0091135472000",
      "score": 1,
      "initialTime": "2022-08-17T15:48:47.561660762",
      "finalTime": "2022-08-17T15:48:48.462660762",
      "_id": "62fd38376f2a2de7a412b761"
    },
    {
      "idAnswerSelected": "6307da6e19a0091135472238",
      "idQuestion": "6307da6e19a00911354722b0",
      "idExercise": "6307da3619a0091135472000",
      "score": 1,
      "initialTime": "2022-08-17T15:48:47.561660762",
      "finalTime": "2022-08-17T15:48:48.462660762",
      "_id": "62fd38376f2a2de7a412b761"
    }
  ]
}
###
GET http://localhost:4000/reports/
###
GET http://localhost:4000/reports/getPopulated/6307db4319a0091135472475
###
DELETE http://localhost:4000/reports/6313fe489f8d55cc33ff3383

###
GET http://localhost:4000/reports/generateModelDataCSV
Content-Type: application/json

{
  "code_model": "skill_model_unificado"
}



###
GET http://localhost:4000/models/
###
GET http://localhost:4000/models/active
###
POST http://localhost:4000/models/fromFile
Content-Type: application/json

{
  "model": "semi_unificado"
}
###
DELETE http://localhost:4000/models/all