GET http://localhost:4000/candos/
###

GET http://localhost:4000/candos/ByLevel/B1
###

POST http://localhost:4000/candos/
Content-Type: application/json

{
  "number": 2,
  "name": "Reconhecer caracteres japoneses: Katakana",
  "lesson": "Lição 2",
  "level": "A1"
}
###

PUT http://localhost:4000/candos/624da61957237cfac075b841
Content-Type: application/json

{
  "number": 1,
  "name": "Reconhecer caracteres japoneses: Hiragana",
  "lesson": "Lição 1",
  "level": "A1"
}
###

DELETE http://localhost:4000/candos/624e10f9cc50bdb65ac2b648



###
GET http://localhost:4000/questions/getPopulated/62fbacbfd1989ee7da430393
###

###
GET http://localhost:4000/answers/
###
GET http://localhost:4000/questions/62fc3e4e8123a75f0d67c477
###
DELETE http://localhost:4000/answers/all
###
DELETE http://localhost:4000/questions/all
###




GET http://localhost:4000/exercises/
###
GET http://localhost:4000/exercises/624e110bcc50bdb65ac2b64a
###
GET http://localhost:4000/exercises/ByCanDo/62fadd49340a4fa60d0c4f50
###


GET http://localhost:4000/exercises/getPopulated/ByCanDo/62fadd57340a4fa60d0c4f52
###
GET http://localhost:4000/exercises/createQuestionsDB/ByCanDo/62fadd57340a4fa60d0c4f52
###

POST http://localhost:4000/exercises/
Content-Type: application/json
{
  "index_val": 1,
    "name": "Leitura de Hiragana #2",
    "description": "Escolha a alternativa correta com a leitura em ROMAJI e significado em PORTUGUÊS.",
    "questions": [
      {
        "question": "あさ",
        "skill_model_a": 1,
        "skill_model_b": 1,
        "skill_model_c": 1,
        "answers": [
          {
            "text": "ASA - Manhã",
            "correct": true,
            "_id": "62ced00c18fbfdd252508663"
          },
          {
            "text": "SAN - Três",
            "correct": false,
            "_id": "62ced00c18fbfdd252508664"
          },
          {
            "text": "HIRU - Tarde",
            "correct": false,
            "_id": "62ced00c18fbfdd252508665"
          },
          {
            "text": "YORU - Noite",
            "correct": false,
            "_id": "62ced00c18fbfdd252508666"
          }
        ],
        "_id": "62ced00c18fbfdd252508662"
      },
      {
        "question": "いち",
        "skill_model_a": 1,
        "skill_model_b": 1,
        "skill_model_c": 1,
        "answers": [
          {
            "text": "YORU - Noite",
            "correct": false,
            "_id": "62ced00c18fbfdd252508668"
          },
          {
            "text": "IE - Casa",
            "correct": false,
            "_id": "62ced00c18fbfdd252508669"
          },
          {
            "text": "ICHI - Um",
            "correct": true,
            "_id": "62ced00c18fbfdd25250866a"
          },
          {
            "text": "YAMA - Montanha",
            "correct": false,
            "_id": "62ced00c18fbfdd25250866b"
          }
        ],
        "_id": "62ced00c18fbfdd252508667"
      },
      {
        "question": "いえ",
        "skill_model_a": 1,
        "skill_model_b": 1,
        "skill_model_c": 1,
        "answers": [
          {
            "text": "ICHI - Um",
            "correct": false,
            "_id": "62ced00c18fbfdd25250866d"
          },
          {
            "text": "IE - Casa",
            "correct": true,
            "_id": "62ced00c18fbfdd25250866e"
          },
          {
            "text": "NEKO - Gato",
            "correct": false,
            "_id": "62ced00c18fbfdd25250866f"
          },
          {
            "text": "SORA - Céu",
            "correct": false,
            "_id": "62ced00c18fbfdd252508670"
          }
        ],
        "_id": "62ced00c18fbfdd25250866c"
      },
      {
        "question": "いす",
        "skill_model_a": 1,
        "skill_model_b": 1,
        "skill_model_c": 1,
        "answers": [
          {
            "text": "ISU - Cadeira",
            "correct": true,
            "_id": "62ced00c18fbfdd252508672"
          },
          {
            "text": "HON - Livro",
            "correct": false,
            "_id": "62ced00c18fbfdd252508673"
          },
          {
            "text": "INU - Cachorro",
            "correct": false,
            "_id": "62ced00c18fbfdd252508674"
          },
          {
            "text": "IE - Casa",
            "correct": false,
            "_id": "62ced00c18fbfdd252508675"
          }
        ],
        "_id": "62ced00c18fbfdd252508671"
      },
      {
        "question": "ざっし",
        "skill_model_a": 1,
        "skill_model_b": 1,
        "skill_model_c": 1,
        "answers": [
          {
            "text": "ZATSUSHI - Caderno",
            "correct": false,
            "_id": "62ced00c18fbfdd252508677"
          },
          {
            "text": "SASSHI - Revista",
            "correct": false,
            "_id": "62ced00c18fbfdd252508678"
          },
          {
            "text": "ZASSHI - Revista",
            "correct": true,
            "_id": "62ced00c18fbfdd252508679"
          },
          {
            "text": "ZACCHI - Caderno",
            "correct": false,
            "_id": "62ced00c18fbfdd25250867a"
          }
        ],
        "_id": "62ced00c18fbfdd252508676"
      },
      {
        "question": "そら",
        "skill_model_a": 1,
        "skill_model_b": 1,
        "skill_model_c": 1,
        "answers": [
          {
            "text": "UMI - Oceano",
            "correct": false,
            "_id": "62ced00c18fbfdd25250867c"
          },
          {
            "text": "SORA - Céu",
            "correct": true,
            "_id": "62ced00c18fbfdd25250867d"
          },
          {
            "text": "NEKO - Gato",
            "correct": false,
            "_id": "62ced00c18fbfdd25250867e"
          },
          {
            "text": "HIRU - Noite",
            "correct": false,
            "_id": "62ced00c18fbfdd25250867f"
          }
        ],
        "_id": "62ced00c18fbfdd25250867b"
      },
      {
        "question": "おちゃ",
        "skill_model_a": 1,
        "skill_model_b": 1,
        "skill_model_c": 1,
        "answers": [
          {
            "text": "UMI - Oceano",
            "correct": false,
            "_id": "62ced00c18fbfdd252508681"
          },
          {
            "text": "OCHA - Chá",
            "correct": true,
            "_id": "62ced00c18fbfdd252508682"
          },
          {
            "text": "ZASSHI - Revista",
            "correct": false,
            "_id": "62ced00c18fbfdd252508683"
          },
          {
            "text": "HON - Livro",
            "correct": false,
            "_id": "62ced00c18fbfdd252508684"
          }
        ],
        "_id": "62ced00c18fbfdd252508680"
      },
      {
        "question": "に",
        "skill_model_a": 1,
        "skill_model_b": 1,
        "skill_model_c": 1,
        "answers": [
          {
            "text": "NI - Dois",
            "correct": true,
            "_id": "62ced00c18fbfdd252508686"
          },
          {
            "text": "SAN - Três",
            "correct": false,
            "_id": "62ced00c18fbfdd252508687"
          },
          {
            "text": "CHA - Chá",
            "correct": false,
            "_id": "62ced00c18fbfdd252508688"
          },
          {
            "text": "IE - Casa",
            "correct": false,
            "_id": "62ced00c18fbfdd252508689"
          }
        ],
        "_id": "62ced00c18fbfdd252508685"
      },
      {
        "question": "れい",
        "skill_model_a": 1,
        "skill_model_b": 1,
        "skill_model_c": 1,
        "answers": [
          {
            "text": "UMI - Oceano",
            "correct": false,
            "_id": "62ced00c18fbfdd25250868b"
          },
          {
            "text": "NEKO - Gato",
            "correct": false,
            "_id": "62ced00c18fbfdd25250868c"
          },
          {
            "text": "SAN - Três",
            "correct": false,
            "_id": "62ced00c18fbfdd25250868d"
          },
          {
            "text": "REI - Exemplo",
            "correct": true,
            "_id": "62ced00c18fbfdd25250868e"
          }
        ],
        "_id": "62ced00c18fbfdd25250868a"
      },
      {
        "question": "かぞく",
        "skill_model_a": 1,
        "skill_model_b": 1,
        "skill_model_c": 1,
        "answers": [
          {
            "text": "KANJI - Kanji",
            "correct": false,
            "_id": "62ced00c18fbfdd252508690"
          },
          {
            "text": "KATAKANA - Katakana",
            "correct": false,
            "_id": "62ced00c18fbfdd252508691"
          },
          {
            "text": "KAZOKU - Família",
            "correct": true,
            "_id": "62ced00c18fbfdd252508692"
          },
          {
            "text": "TOKEI - Relógio",
            "correct": false,
            "_id": "62ced00c18fbfdd252508693"
          }
        ],
        "_id": "62ced00c18fbfdd25250868f"
      },
      {
        "question": "ねこ",
        "skill_model_a": 1,
        "skill_model_b": 1,
        "skill_model_c": 1,
        "answers": [
          {
            "text": "NEKO - Gato",
            "correct": true,
            "_id": "62ced00c18fbfdd252508695"
          },
          {
            "text": "KANJI - Kanji",
            "correct": false,
            "_id": "62ced00c18fbfdd252508696"
          },
          {
            "text": "SAN - Três",
            "correct": false,
            "_id": "62ced00c18fbfdd252508697"
          },
          {
            "text": "REI - Exemplo",
            "correct": false,
            "_id": "62ced00c18fbfdd252508698"
          }
        ],
        "_id": "62ced00c18fbfdd252508694"
      },
      {
        "question": "ひらがな",
        "skill_model_a": 1,
        "skill_model_b": 1,
        "skill_model_c": 1,
        "answers": [
          {
            "text": "KATAKANA - Katakana",
            "correct": false,
            "_id": "62ced00c18fbfdd25250869a"
          },
          {
            "text": "HIRAGANA - Hiragana",
            "correct": true,
            "_id": "62ced00c18fbfdd25250869b"
          },
          {
            "text": "FUJISAN - Monte Fuji",
            "correct": false,
            "_id": "62ced00c18fbfdd25250869c"
          },
          {
            "text": "TENPURA - Tempura",
            "correct": false,
            "_id": "62ced00c18fbfdd25250869d"
          }
        ],
        "_id": "62ced00c18fbfdd252508699"
      },
      {
        "question": "しんぶん",
        "skill_model_a": 1,
        "skill_model_b": 1,
        "skill_model_c": 1,
        "answers": [
          {
            "text": "TENPURA - Tempura",
            "correct": false,
            "_id": "62ced00c18fbfdd25250869f"
          },
          {
            "text": "HIRAGANA - Hiragana",
            "correct": false,
            "_id": "62ced00c18fbfdd2525086a0"
          },
          {
            "text": "SHINBUN - Jornal",
            "correct": true,
            "_id": "62ced00c18fbfdd2525086a1"
          },
          {
            "text": "KATAKANA - Katakana",
            "correct": false,
            "_id": "62ced00c18fbfdd2525086a2"
          }
        ],
        "_id": "62ced00c18fbfdd25250869e"
      },
      {
        "question": "かんじ",
        "skill_model_a": 1,
        "skill_model_b": 1,
        "skill_model_c": 1,
        "answers": [
          {
            "text": "SUUJI - Número",
            "correct": false,
            "_id": "62ced00c18fbfdd2525086a4"
          },
          {
            "text": "KANJI - Kanji",
            "correct": true,
            "_id": "62ced00c18fbfdd2525086a5"
          },
          {
            "text": "TSUKUE - Mesa",
            "correct": false,
            "_id": "62ced00c18fbfdd2525086a6"
          },
          {
            "text": "YASAI - Vegetal",
            "correct": false,
            "_id": "62ced00c18fbfdd2525086a7"
          }
        ],
        "_id": "62ced00c18fbfdd2525086a3"
      },
      {
        "question": "にほんご",
        "skill_model_a": 1,
        "skill_model_b": 1,
        "skill_model_c": 1,
        "answers": [
          {
            "text": "TAMAGO - Ovo",
            "correct": false,
            "_id": "62ced00c18fbfdd2525086a9"
          },
          {
            "text": "TENPURA - Tempura",
            "correct": false,
            "_id": "62ced00c18fbfdd2525086aa"
          },
          {
            "text": "TOKEI - Relógio",
            "correct": false,
            "_id": "62ced00c18fbfdd2525086ab"
          },
          {
            "text": "NIHONGO - Idioma japonês",
            "correct": true,
            "_id": "62ced00c18fbfdd2525086ac"
          }
        ],
        "_id": "62ced00c18fbfdd2525086a8"
      },
      {
        "question": "ほん",
        "skill_model_a": 1,
        "skill_model_b": 1,
        "skill_model_c": 1,
        "answers": [
          {
            "text": "SORA - Mar",
            "correct": false,
            "_id": "62ced00c18fbfdd2525086ae"
          },
          {
            "text": "HAI - Sim",
            "correct": false,
            "_id": "62ced00c18fbfdd2525086af"
          },
          {
            "text": "UMI - Mar",
            "correct": false,
            "_id": "62ced00c18fbfdd2525086b0"
          },
          {
            "text": "HON - Livro",
            "correct": true,
            "_id": "62ced00c18fbfdd2525086b1"
          }
        ],
        "_id": "62ced00c18fbfdd2525086ad"
      },
      {
        "question": "うみ",
        "skill_model_a": 1,
        "skill_model_b": 1,
        "skill_model_c": 1,
        "answers": [
          {
            "text": "HON - Livro",
            "correct": false,
            "_id": "62ced00c18fbfdd2525086b3"
          },
          {
            "text": "UMI - Mar",
            "correct": true,
            "_id": "62ced00c18fbfdd2525086b4"
          },
          {
            "text": "HAI - Sim",
            "correct": false,
            "_id": "62ced00c18fbfdd2525086b5"
          },
          {
            "text": "ICHI - Um",
            "correct": false,
            "_id": "62ced00c18fbfdd2525086b6"
          }
        ],
        "_id": "62ced00c18fbfdd2525086b2"
      },
      {
        "question": "つくえ",
        "skill_model_a": 1,
        "skill_model_b": 1,
        "skill_model_c": 1,
        "answers": [
          {
            "text": "TSUKUE - Mesa",
            "correct": true,
            "_id": "62ced00c18fbfdd2525086b8"
          },
          {
            "text": "TAMAGO - Ovo",
            "correct": false,
            "_id": "62ced00c18fbfdd2525086b9"
          },
          {
            "text": "IIE - Não",
            "correct": false,
            "_id": "62ced00c18fbfdd2525086ba"
          },
          {
            "text": "TOKEI - Relógio",
            "correct": false,
            "_id": "62ced00c18fbfdd2525086bb"
          }
        ],
        "_id": "62ced00c18fbfdd2525086b7"
      },
      {
        "question": "やま",
        "skill_model_a": 1,
        "skill_model_b": 1,
        "skill_model_c": 1,
        "answers": [
          {
            "text": "HIRU - Tarde",
            "correct": false,
            "_id": "62ced00c18fbfdd2525086bd"
          },
          {
            "text": "YORU - Noite",
            "correct": false,
            "_id": "62ced00c18fbfdd2525086be"
          },
          {
            "text": "YAMA - Montanha",
            "correct": true,
            "_id": "62ced00c18fbfdd2525086bf"
          },
          {
            "text": "NEKO - Gato",
            "correct": false,
            "_id": "62ced00c18fbfdd2525086c0"
          }
        ],
        "_id": "62ced00c18fbfdd2525086bc"
      },
      {
        "question": "ふじさん",
        "skill_model_a": 1,
        "skill_model_b": 1,
        "skill_model_c": 1,
        "answers": [
          {
            "text": "SAKANA - Peixe",
            "correct": false,
            "_id": "62ced00c18fbfdd2525086c2"
          },
          {
            "text": "FUJISAN - Monte Fuji",
            "correct": true,
            "_id": "62ced00c18fbfdd2525086c3"
          },
          {
            "text": "TOUKYOU - Tókio",
            "correct": false,
            "_id": "62ced00c18fbfdd2525086c4"
          },
          {
            "text": "NIHONGO - Idioma Japonês",
            "correct": false,
            "_id": "62ced00c18fbfdd2525086c5"
          }
        ],
        "_id": "62ced00c18fbfdd2525086c1"
      },
      {
        "question": "いいえ",
        "skill_model_a": 1,
        "skill_model_b": 1,
        "skill_model_c": 1,
        "answers": [
          {
            "text": "HAI - Sim",
            "correct": false,
            "_id": "62ced00c18fbfdd2525086c7"
          },
          {
            "text": "REI - Exemplo",
            "correct": false,
            "_id": "62ced00c18fbfdd2525086c8"
          },
          {
            "text": "ICHI - Um",
            "correct": false,
            "_id": "62ced00c18fbfdd2525086c9"
          },
          {
            "text": "IIE - Não",
            "correct": true,
            "_id": "62ced00c18fbfdd2525086ca"
          }
        ],
        "_id": "62ced00c18fbfdd2525086c6"
      },
      {
        "question": "よる",
        "skill_model_a": 1,
        "skill_model_b": 1,
        "skill_model_c": 1,
        "answers": [
          {
            "text": "HIRU - Tarde",
            "correct": false,
            "_id": "62ced00c18fbfdd2525086cc"
          },
          {
            "text": "YORU - Noite",
            "correct": true,
            "_id": "62ced00c18fbfdd2525086cd"
          },
          {
            "text": "YAMA - Montanha",
            "correct": false,
            "_id": "62ced00c18fbfdd2525086ce"
          },
          {
            "text": "NEKO - Gato",
            "correct": false,
            "_id": "62ced00c18fbfdd2525086cf"
          }
        ],
        "_id": "62ced00c18fbfdd2525086cb"
      },
      {
        "question": "すうじ",
        "skill_model_a": 1,
        "skill_model_b": 1,
        "skill_model_c": 1,
        "answers": [
          {
            "text": "KANJI - Kanji",
            "correct": false,
            "_id": "62ced00c18fbfdd2525086d1"
          },
          {
            "text": "SUUJI - Número",
            "correct": true,
            "_id": "62ced00c18fbfdd2525086d2"
          },
          {
            "text": "UMI - Mar",
            "correct": false,
            "_id": "62ced00c18fbfdd2525086d3"
          },
          {
            "text": "TOKEI - Relógio",
            "correct": false,
            "_id": "62ced00c18fbfdd2525086d4"
          }
        ],
        "_id": "62ced00c18fbfdd2525086d0"
      },
      {
        "question": "たまご",
        "skill_model_a": 1,
        "skill_model_b": 1,
        "skill_model_c": 1,
        "answers": [
          {
            "text": "TAMAGO - Ovo",
            "correct": true,
            "_id": "62ced00d18fbfdd2525086d6"
          },
          {
            "text": "TOKEI - Relógio",
            "correct": false,
            "_id": "62ced00d18fbfdd2525086d7"
          },
          {
            "text": "YASAI - Vegetal",
            "correct": false,
            "_id": "62ced00d18fbfdd2525086d8"
          },
          {
            "text": "KANJI - Kanji",
            "correct": false,
            "_id": "62ced00d18fbfdd2525086d9"
          }
        ],
        "_id": "62ced00d18fbfdd2525086d5"
      },
      {
        "question": "さかな",
        "skill_model_a": 1,
        "skill_model_b": 1,
        "skill_model_c": 1,
        "answers": [
          {
            "text": "TSUKUE - Mesa",
            "correct": false,
            "_id": "62ced00d18fbfdd2525086db"
          },
          {
            "text": "TAMAGO - Ovo",
            "correct": false,
            "_id": "62ced00d18fbfdd2525086dc"
          },
          {
            "text": "TOKEI - Relógio",
            "correct": false,
            "_id": "62ced00d18fbfdd2525086dd"
          },
          {
            "text": "SAKANA - Peixe",
            "correct": true,
            "_id": "62ced00d18fbfdd2525086de"
          }
        ],
        "_id": "62ced00d18fbfdd2525086da"
      },
      {
        "question": "とけい",
        "skill_model_a": 1,
        "skill_model_b": 1,
        "skill_model_c": 1,
        "answers": [
          {
            "text": "TSUKUE - Mesa",
            "correct": false,
            "_id": "62ced00d18fbfdd2525086e0"
          },
          {
            "text": "TAMAGO - Ovo",
            "correct": false,
            "_id": "62ced00d18fbfdd2525086e1"
          },
          {
            "text": "TOKEI - Relógio",
            "correct": true,
            "_id": "62ced00d18fbfdd2525086e2"
          },
          {
            "text": "SAKANA - Peixe",
            "correct": false,
            "_id": "62ced00d18fbfdd2525086e3"
          }
        ],
        "_id": "62ced00d18fbfdd2525086df"
      },
      {
        "question": "はい",
        "skill_model_a": 1,
        "skill_model_b": 1,
        "skill_model_c": 1,
        "answers": [
          {
            "text": "HAI - Sim",
            "correct": true,
            "_id": "62ced00d18fbfdd2525086e5"
          },
          {
            "text": "HON - Livro",
            "correct": false,
            "_id": "62ced00d18fbfdd2525086e6"
          },
          {
            "text": "YORU - Noite",
            "correct": false,
            "_id": "62ced00d18fbfdd2525086e7"
          },
          {
            "text": "IE - Casa",
            "correct": false,
            "_id": "62ced00d18fbfdd2525086e8"
          }
        ],
        "_id": "62ced00d18fbfdd2525086e4"
      },
      {
        "question": "ひる",
        "skill_model_a": 1,
        "skill_model_b": 1,
        "skill_model_c": 1,
        "answers": [
          {
            "text": "YORU - Noite",
            "correct": false,
            "_id": "62ced00d18fbfdd2525086ea"
          },
          {
            "text": "HIRU - Tarde",
            "correct": true,
            "_id": "62ced00d18fbfdd2525086eb"
          },
          {
            "text": "SORA - Céu",
            "correct": false,
            "_id": "62ced00d18fbfdd2525086ec"
          },
          {
            "text": "ICHI - Um",
            "correct": false,
            "_id": "62ced00d18fbfdd2525086ed"
          }
        ],
        "_id": "62ced00d18fbfdd2525086e9"
      },
      {
        "question": "てんぷら",
        "skill_model_a": 1,
        "skill_model_b": 1,
        "skill_model_c": 1,
        "answers": [
          {
            "text": "TOUKYOU - Tókio",
            "correct": false,
            "_id": "62ced00d18fbfdd2525086ef"
          },
          {
            "text": "OCHA - Chá",
            "correct": false,
            "_id": "62ced00d18fbfdd2525086f0"
          },
          {
            "text": "FUJISAN - Monte Fuji",
            "correct": false,
            "_id": "62ced00d18fbfdd2525086f1"
          },
          {
            "text": "TENPURA - Tempura",
            "correct": true,
            "_id": "62ced00d18fbfdd2525086f2"
          }
        ],
        "_id": "62ced00d18fbfdd2525086ee"
      },
      {
        "question": "とうきょう",
        "skill_model_a": 1,
        "skill_model_b": 1,
        "skill_model_c": 1,
        "answers": [
          {
            "text": "TENPURA - Tempura",
            "correct": false,
            "_id": "62ced00d18fbfdd2525086f4"
          },
          {
            "text": "TAMAGO - Ovo",
            "correct": false,
            "_id": "62ced00d18fbfdd2525086f5"
          },
          {
            "text": "TOUKYOU - Tókio",
            "correct": true,
            "_id": "62ced00d18fbfdd2525086f6"
          },
          {
            "text": "TOKEI - Relógio",
            "correct": false,
            "_id": "62ced00d18fbfdd2525086f7"
          }
        ],
        "_id": "62ced00d18fbfdd2525086f3"
      },
      {
        "question": "さん",
        "skill_model_a": 1,
        "skill_model_b": 1,
        "skill_model_c": 1,
        "answers": [
          {
            "text": "SAN - Três",
            "correct": true,
            "_id": "62ced00d18fbfdd2525086f9"
          },
          {
            "text": "HON - Livro",
            "correct": false,
            "_id": "62ced00d18fbfdd2525086fa"
          },
          {
            "text": "HAI - Sim",
            "correct": false,
            "_id": "62ced00d18fbfdd2525086fb"
          },
          {
            "text": "SORA - Céu",
            "correct": false,
            "_id": "62ced00d18fbfdd2525086fc"
          }
        ],
        "_id": "62ced00d18fbfdd2525086f8"
      },
      {
        "question": "やさい",
        "skill_model_a": 1,
        "skill_model_b": 1,
        "skill_model_c": 1,
        "answers": [
          {
            "text": "YORU - Noite",
            "correct": false,
            "_id": "62ced00d18fbfdd2525086fe"
          },
          {
            "text": "YASAI - Vegetal",
            "correct": true,
            "_id": "62ced00d18fbfdd2525086ff"
          },
          {
            "text": "TOKEI - Relógio",
            "correct": false,
            "_id": "62ced00d18fbfdd252508700"
          },
          {
            "text": "YAMA - Montanha",
            "correct": false,
            "_id": "62ced00d18fbfdd252508701"
          }
        ],
        "_id": "62ced00d18fbfdd2525086fd"
      }
    ],
    "cando_id": "62fadd49340a4fa60d0c4f50"
}
###

PUT http://localhost:4000/exercises/62fba86035e8d585042a7802
Content-Type: application/json

{

}
###

DELETE http://localhost:4000/exercises/624ee0b2ce17e94b1c17d5ab
###


POST http://localhost:4000/reports/
Content-Type: application/json

{
  "idUser": "62b4edfcb22b0cf44db5e5ff",
  "idCanDo": "62b9d72d8c02c34b14723195",
  "answers": [
    {
      "idAnswerSelected": "62fc3e4e8123a75f0d67c377",
      "idQuestion": "62fc3e4e8123a75f0d67c477",
      "idExercise": "62fc3e2d8123a75f0d67c2d2",
      "score": 1,
      "initialTime": "2022-08-17T15:48:47.561660762",
      "finalTime": "2022-08-17T15:48:48.462660762",
      "_id": "62fd38376f2a2de7a412b760"
    }
  ]
}
###
GET http://localhost:4000/reports/62fd3e947fe264010bbf6f0a
###
GET http://localhost:4000/reports/getPopulated/62fd3e947fe264010bbf6f0a
###
DELETE http://localhost:4000/reports/625c8a9b15c76579ae381025