GET https://tccmarcioconceito.herokuapp.com/answers/
###

POST https://tccmarcioconceito.herokuapp.com/answers/
Content-Type: application/json

{
  "text": "primeiro texto"
}
###

PUT https://tccmarcioconceito.herokuapp.com/answers/62f188336e77215e6fbd358a
Content-Type: application/json

{
    "text": "update"
}
###

DELETE https://tccmarcioconceito.herokuapp.com/answers/62f188336e77215e6fbd358a
###







GET https://tccmarcioconceito.herokuapp.com/questions/
###

POST https://tccmarcioconceito.herokuapp.com/questions/
Content-Type: application/json

{
    "question": "texto da questao",
    "answers": [
      {
        "idAnswer": "62f188336e77215e6fbd358a",
        "correct": true
      }
    ]
}
###

PUT https://tccmarcioconceito.herokuapp.com/questions/62f188336e77215e6fbd358a
Content-Type: application/json

{
    "question": "update da questao",
    "answers": [
      {
        "idAnswer": "62f188336e77215e6fbd358a",
        "correct": false
      }
    ]
}
###

DELETE https://tccmarcioconceito.herokuapp.com/questions/62f188336e77215e6fbd358a