GET https://tccmarcioconceito.herokuapp.com/answers/
###

POST https://tccmarcioconceito.herokuapp.com/answers/
Content-Type: application/json

{
  "text": "segundo texto"
}
###

PUT https://tccmarcioconceito.herokuapp.com/answers/62f188336e77215e6fbd358a
Content-Type: application/json

{
    "text": "primeiro texto"
}
###

DELETE https://tccmarcioconceito.herokuapp.com/answers/62f188336e77215e6fbd358a
###







GET https://tccmarcioconceito.herokuapp.com/questions/
###
GET https://tccmarcioconceito.herokuapp.com/questions/62f18f075c280d01a85e327b
###

GET https://tccmarcioconceito.herokuapp.com/questions/getPopulated
###
GET https://tccmarcioconceito.herokuapp.com/questions/getPopulated/62f18f075c280d01a85e327b
###

POST https://tccmarcioconceito.herokuapp.com/questions/
Content-Type: application/json

{
    "question": "texto da questao",
    "answers": [
      {
        "idAnswer": "62f188336e77215e6fbd358a",
        "correct": true
      },
      {
        "idAnswer": "62f18b1770f1da8e47535e3f",
        "correct": true
      }
    ]
}
###

PUT https://tccmarcioconceito.herokuapp.com/questions/62f18f075c280d01a85e327b
Content-Type: application/json

{
    "question": "update da questao",
    "answers": [
      {
        "idAnswer": "62f188336e77215e6fbd358a",
        "correct": false
      },
      {
        "idAnswer": "62f18b1770f1da8e47535e3f",
        "correct": false
      }
    ]
}
###

DELETE https://tccmarcioconceito.herokuapp.com/questions/62f18f075c280d01a85e327b